matrix:
  include:
    # Build for Ubuntu using Dockerfile
    - language: c
      sudo: required
      services:
        - docker
      install:
        - cd docker/ubuntu/
        - docker build -t ubuntu .
        - cd ../..
      script:
        - export MAKEFLAGS="-j$((`grep -c ^processor /proc/cpuinfo`*2))"
        - docker run --rm -v $(pwd):/code ubuntu ./autogen.sh
        - docker run --rm -v $(pwd):/code ubuntu ./configure
        - docker run --rm -v $(pwd):/code ubuntu make
        - docker run --rm -v $(pwd):/code ubuntu make check
        - docker run --rm -v $(pwd):/code ubuntu make install

    # Build for macOS
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew install gettext
        - brew install asciidoc
        - wget https://tug.org/cgi-bin/mactex-download/BasicTeX.pkg && pkgutil --check-signature BasicTeX.pkg && sudo installer -pkg BasicTeX.pkg -target /
      script:
        - cd macosx/
        - xcodebuild clean build -project Warzone.xcodeproj -target Warzone -configuration Release -destination "platform=macOS"
