matrix:
  include:
    ## Build for Ubuntu using Dockerfile
    ## Commented out until Ubuntu Dockerfile can be fixed for SDL >= 2.0.5
    #- language: c
    #  sudo: required
    #  services:
    #    - docker
    #  install:
    #    - cd docker/ubuntu/
    #    - docker build -t ubuntu .
    #    - cd ../..
    #  script:
    #    - export MAKEFLAGS="-j$((`grep -c ^processor /proc/cpuinfo`*2))"
    #    - docker run --rm -v $(pwd):/code ubuntu ./autogen.sh
    #    - docker run --rm -v $(pwd):/code ubuntu ./configure
    #    - docker run --rm -v $(pwd):/code ubuntu make
    #    - docker run --rm -v $(pwd):/code ubuntu make check
    #    - docker run --rm -v $(pwd):/code ubuntu make install

    # Build for macOS
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      env:
        # For new public releases, uncomment the following line to include the video sequences in the resulting app bundle
        # - MAC_BUILD_RELEASE=true
	- TRAVIS_MAC_BUILD=true
      before_install:
        #- brew update
        - brew install gettext
        - brew install asciidoc
        - wget https://tug.org/cgi-bin/mactex-download/BasicTeX.pkg && pkgutil --check-signature BasicTeX.pkg && sudo installer -pkg BasicTeX.pkg -target /
        - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
        - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
      script:
        - macosx/BuildBot/00_clean.sh
        - macosx/BuildBot/01_configure.sh
        - macosx/BuildBot/02_compile.sh
      after_success:
        - macosx/BuildBot/03_upload.sh
