# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- test-azure

jobs:
- template: templates/macos-build-pipeline-template.yml  # Template reference
  parameters:
    name: macOS_Xcode_9_4_1
    displayName: 'macOS (CMake) [Xcode 9.4.1, macOS 10.13 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_9.4.1.app'
    publishArtifact: false
- template: templates/macos-build-pipeline-template.yml  # Template reference
  parameters:
    name: macOS_Xcode_10_3
    displayName: 'macOS (CMake) [Xcode 10.3, macOS 10.14 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_10.3.app' # Set default Xcode to Xcode 10.3 on macOS 10.14
    publishArtifact: true
- template: templates/macos-build-pipeline-template.yml  # Template reference
  parameters:
    name: macOS_Xcode_11
    displayName: 'macOS (CMake) [Xcode 11.x, macOS 10.15 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.15'
    publishArtifact: false
- template: templates/macos-build-pipeline-template.yml  # Template reference
  parameters:
    name: macOS_latest
    displayName: 'macOS (CMake) [vmImage: macOS-latest]'  # friendly name to display in the UI
    vmImage: 'macOS-latest'
    publishArtifact: true
